//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CayQD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUTRALOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUTRALOI()
        {
            this.CAUHOI = new HashSet<CAUHOI>();
        }
    
        public int ID { get; set; }
        public string CAUTRALOI1 { get; set; }
        public int ID_CAUHOI { get; set; }
        public bool IS_NUTLA { get; set; }
        public Nullable<int> ID_NGANHHOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAUHOI> CAUHOI { get; set; }
        public virtual NGANHHOC NGANHHOC { get; set; }
    }
}
