//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CayQD
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NGAYGIO { get; set; }
        public string NGUOITHAMGIA { get; set; }
        public string DIACHI { get; set; }
        public string GHICHU { get; set; }
        public string TENDN { get; set; }
        public string MATKHAU { get; set; }
    }
}
