<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="tttnqtm.aspx.cs" Inherits="CayQD._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
</br></br></br></br>Công việc của quản trị mạng</br>
Người quản trị mạng (QTM) phải có khả năng tự thiết lập một mạng máy tính, cấu hình mạng, điều chỉnh hiệu năng hoạt động mạng máy tính, vận hành hệ thống mạng, giải quyết sự cố mạng và nắm được các phương pháp để bảo vệ mạng trước nguy cơ virus, worm, trojan, spam, cũng như các biện pháp chống xâm nhập, ăn cắp thông tin, phá hoại mạng.</br>

Công việc cụ thể của từng chuyên viên QTM sẽ tùy thuộc vào quy mô doanh nghiệp. Thông thường, những doanh nghiệp ứng dụng CNTT quy mô lớn như ngân hàng, bảo hiểm, hàng không, các công ty về lĩnh vực thương mại điện tử cần tới một phòng QTM với số nhân viên lên tới vài chục, thậm chí là hàng trăm. Các doanh nghiệp quy mô vừa cần khoảng 4-5 người, các doanh nghiệp nhỏ cũng cần ít nhất một nhân viên chuyên phụ trách hệ thống mạng. Ở các công ty quy mô nhỏ, số lượng máy tính ít thì người QTM phải biết và làm đủ mọi thứ để duy trì hoạt động thông suốt của mạng, bao gồm cả việc theo dõi cập nhật nội dung của website đơn vị. Trong khi đó, nếu được làm tại các công ty với quy mô lớn, người làm QTM được phân công một công việc cụ thể như QTM chuyên về bảo mật, chuyên về thiết kế mạng hay chuyên về bộ phận theo dõi, giám sát, vận hành máy chủ.</br>

QTM thường chỉ liên quan đến công việc kỹ thuật mạng và hiếm khi phải hỗ trợ trực tiếp người sử dụng. QTM thường là ở cấp 3 trong xử lý sự cố, tức là khi có sự cố xảy ra thì trước tiên sẽ được xử lý ở cấp 1 (helpdesk – giải đáp thắc mắc, tư vấn), cấp 2 (kỹ thuật viên về máy tính và mạng) rồi mới đến cấp 3 là cấp QTM. Tuy vậy, tại rất nhiều công ty ở Việt Nam hiện nay, thậm chí cả một số văn phòng nước ngoài, người QTM thường kiêm nhiệm tất cả các công việc này.</br>
   </br><center> <img src="Hinh/quantrimang.png" /></center></br>
Thông thường các công ty nhỏ cỡ vài chục máy tính sẽ cần khoảng 2 – 3 nhân viên gọi là quản trị mạng nhưng thực chất là làm tất cả các công việc phát sinh như hỗ trợ người dùng, đề xuất và mua sắm trang thiết bị, đi dây và cài đặt mạng cho người dùng mới, xử lý các sự cố như đứt mạng, nghẽn mạng, quản lý băng thông, cấu hình tường lửa bảo vệ… Ở công ty lớn hơn thì phần lớn các công việc trên sẽ do các kỹ thuật viên phòng IT đảm nhiệm, quản trị mạng chỉ lo các phần liên quan đến băng thông và bảo mật mạng, quản lý máy chủ. Còn những công ty nhỏ hơn thì thậm chí cũng không cần đến quản trị mạng mà thuê ngoài, các sự cố nho nhỏ thì nhờ người rành công nghệ tự xử lý”.</br>

Nhu cầu cao, lương khá</br>

Hiện nay, hầu như công ty, doanh nghiệp nào cũng đều có máy tính nối mạng nội bộ và kết nối internet, chưa kể rất nhiều công ty có website riêng hoặc có tham gia bán hàng qua mạng trên các gian hàng trực tuyến. Do đó, nhu cầu tuyển dụng các nhân viên quản trị hệ thống mạng máy tính và kiêm nhiệm quản trị website khá lớn.</br>

Tùy công ty, mức lương cho vị trí QTM có thể từ 200 – 700 USD, thậm chí một số công ty nước ngoài còn trả tới trên 1.000 USD. Trong nghề QTM có nhiều ngạch nhỏ, như QTM chuyên lo bảo mật, chuyên thiết kế mạng, hoặc chuyên về các máy chủ, nên lương cũng trả tùy theo, nói chung lương quản trị bảo mật cao hơn một chút, trung bình vào khoảng 5-7 triệu đồng/tháng, còn những người có khả năng làm luôn bảo mật, lo luôn cho server, quản lý được luôn NT/Samba Domain, thiết kế LAN-WAN thì lương rất cao.</br>

Mặc dù vậy, không phải không có những người thất nghiệp sau khi học xong, lý do được đưa ra là : cần kiến thức về mạng rất rộng, trong khi đòi hỏi của các doanh nghiệp vừa và nhỏ thường đa năng, mỗi thứ một chút, nếu chỉ biết chuyên sâu một thứ thôi thì cũng khó tìm việc làm ở các doanh nghiệp vừa và nhỏ. Hơn nữa, nghề này đòi hỏi phải thực hành nhiều, càng làm nhiều càng có kinh nghiệm thực tế trong xử lý sự cố, vì thế trong quá trình học, bạn phải thật nỗ lực để nắm chắc lý thuyết và cố gắng tận dụng mọi cơ hội để thực hành.</br>

</asp:Content>